# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
x = s.split()

print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {planet} is {diameter} kilometers.".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
import numpy as np
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [17]:
import pandas as pd
pd.DataFrame(index=np.arange(3), columns=np.arange(2))



0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
from datetime import date, timedelta

sdate = date(2023,1,1)  
edate = date(2023,2,10)   

def dates_bwn_twodates(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)
print(dates_bwn_twodates(sdate,edate))

<generator object dates_bwn_twodates at 0x7f730f9fedd0>


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:

import pandas as pd  

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame(lists, columns =['sno','name' ,'number']) 
print(df )

   sno name  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
